//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parqueoEntities : DbContext
    {
        public parqueoEntities()
            : base("name=parqueoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cobros> cobros { get; set; }
        public virtual DbSet<registros> registros { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<tabla> tablas { get; set; }
        public virtual DbSet<vehiculo> vehiculos1 { get; set; }
    }
}
